### PR TITLE
new readme

### LINKED ISSUE #2: in progress
Refer to [Readme](https://github.com/learn-co-curriculum/sql-queries-basic/blob/master/README.md) for outline of content

### PR DESCRIPTION
**Pull request by SophieDeBenedetto**
new reading

closes #2

needs :eyes: 

@AnnJohn @deniznida @aviflombaum @dfenjves @ipc103

### CODE REVIEW

**Comment by AnnJohn** [comment]
Assigning to @aviflombaum 

Deadline: 9/11/15

**Comment by AnnJohn** [comment]
Oops, will unassign you. This is for the Sinatra track

**Comment by AnnJohn** [comment]
@deniznida will review. Deadline- 9/11/15

**Comment by deniznida** [comment]
@SophieDeBenedetto looks really good! Should we also add Conditional Operators like IS NULL and BETWEEN? Both are used in the Sql Bears lab

**Comment by dfenjves** [comment]
I love Maru.

**Pull request merged**
